name: Release

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: fiware/ishare-satellite
  IMAGE_NAME_QUAY: quay.io/fiware/ishare-satellite

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest


  generate-version:
    name: Generate version
    needs: ["test"]
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.out.outputs.version }}

    steps:
      - uses: actions/checkout@v2

      - id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: ${{ steps.pr.outputs.labels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version output
        id: out
        run: echo "::set-output name=version::$(echo ${VERSION})"


  git-release:
    name: Git release
    needs: ["test", "generate-version"]
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ needs.generate-version.outputs.version }}
          title: ${{ needs.generate-version.outputs.version }}
          prerelease: false
          files: |
            LICENSE

  
  docker-release:
    name: Docker build and release
    needs: ["test", "git-release", "generate-version"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        run: |
          docker build --tag ${{ env.IMAGE_NAME }}:${{ needs.generate-version.outputs.version }} .
  
          docker push ${{ env.IMAGE_NAME }}:${{ needs.generate-version.outputs.version }}
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.generate-version.outputs.version }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Push to quay.io
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin
          docker tag ${{ env.IMAGE_NAME }}:${{ needs.generate-version.outputs.version }} ${{ env.IMAGE_NAME_QUAY }}:${{ needs.generate-version.outputs.version }}
          docker push ${{ env.IMAGE_NAME_QUAY }}:${{ needs.generate-version.outputs.version }}
          docker tag ${{ env.IMAGE_NAME_QUAY }}:${{ needs.generate-version.outputs.version }} ${{ env.IMAGE_NAME_QUAY }}:latest
          docker push ${{ env.IMAGE_NAME_QUAY }}:latest
